### ISSUE TITLE
listPresentations.pyで作成されるpresen.csvにdate情報が含まれていない．

### ISSUE THREAD

**Issue by Ikuzus-k** [chiemi627/deimscripts#1]
listPresentations.pyで作成できるcsvファイルにdateのカラムが入っていない．

PosTom上で必要なフォーマットは以下であるが，
room, session_order, presentation_order, date, title, abstract, keyword, authors_name, authors_belongs
４カラム目のdateが生成されていない．

**Comment by chiemi627** [comment]
@Ikuzus-k 確認できたらクローズしてください〜

**Comment by Ikuzus-k** [comment]
確認できました！
ありがとうございます
